server:
  port: 8888
  servlet:
    context-path: /highset
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30

spring:
  #\u6570\u636E\u6E90
  datasource:
    url: jdbc:postgresql://139.9.47.39:8888/vbcrm?currentSchema=vbcrm
    username: vbcrm
    password: Vbcrm@2021
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  redis:
    host: 127.0.0.1
    #    password: 123456
    # \u6570\u636E\u5E93\u7D22\u5F15 \u9ED8\u8BA40
    database: 0
    port: 6379

# \u9700\u8981\u9A8C\u8BC1\u7801\u6821\u9A8C\u7684\u63A5\u53E3\u8DEF\u5F84 \u652F\u6301\u901A\u914D\u7B26 \u81EA\u52A8\u8FC7\u6EE4\u62E6\u622A\u6821\u9A8C \u65E0\u9700\u5F00\u53D1\u4EBA\u5458\u518D\u6B21\u6821\u9A8C
captcha:
  # \u56FE\u7247\u9A8C\u8BC1\u7801\u9A8C\u8BC1
  image:
    - /login # \u767B\u5F55\u63A5\u53E3
    - /social/relate # \u7ED1\u5B9A\u7B2C\u4E09\u65B9\u8D26\u53F7

# \u5FFD\u7565\u9274\u6743url
ignored:
  urls:
    - /common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
# Actuator
management:
  health:
    status:
      http-mapping:
        DOWN: 200
        OUT_OF_SERVICE: 200
        FATAL: 200
        UNKNOWN: 200
    # \u6682\u672A\u7528\u5230ES \u5173\u95ED\u5176\u5065\u5EB7\u68C0\u67E5
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /highset/actuator/
      exposure:
        include: '*'
# Swagger\u754C\u9762\u5185\u5BB9\u914D\u7F6E
swagger:
  title: Highset API\u63A5\u53E3\u6587\u6863
  description: Highset Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://www.highset.cn
  contact:
    name: Victor
    url: http://www.highset.cn
    email: jiabin.zhao@.highset.cn


#mybatis-plus
mybatis-plus:
  #\u5168\u5C40\u914D\u7F6E
  global-config:
    #\u6570\u636E\u5E93\u914D\u7F6E
    db-config:
      # \u5168\u5C40\u5220\u9664\u6807\u5FD7 \uFF0C\uFF0C\u4E0D\u7528\u4FEE\u6539
      logic-delete-field: flag
      # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-delete-value: 1
      # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
      logic-not-delete-value: 0
  #mybatis-plus\u6253\u5370SQL\u8BED\u53E5
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml